name: telecom_churn_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^0.13.3
  provider: ^6.0.0
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.1
  flutter_chat_ui: ^1.6.15
  flutter_animate: ^4.3.0
  file_picker: ^8.3.1
  csv: ^6.0.0
  fl_chart: ^0.70.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^0.4.5+4
  flutter_riverpod: ^2.0.2
  path_provider: ^2.1.2
  flutter_web_plugins:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Telecom-Customer-Churn.csv
    - assets/telecom_churn.db
